[package]
name = "rss-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.16"
rss = "2.0.3"
tokio = {version="1.28.0", features=["full"]}
shared = {path = "../shared"}
