[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
name = "shared"
crate-type = ["lib"]

[dependencies]
chrono = "0.4.24"
rss = "2.0.3"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
